<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Web Inspector (Log)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>mcol_339900FF.settings</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.settings</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.settings</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\[D\])\s(.*?):(\d+)\s</string>
			<key>name</key>
			<string>jsd.log.debug</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>mcol_CC0000FF.settings</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.settings</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.settings</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\[E\])\s(.*?):(\d+)\s</string>
			<key>name</key>
			<string>jsd.log.error</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>mcol_F93F07FF.settings</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.settings</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.settings</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\[W\])\s(.*?):(\d+)\s</string>
			<key>name</key>
			<string>jsd.log.warn</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>mcol_0088CCFF.settings</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.settings</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.settings</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\[L\])\s(.*?):(\d+)\s</string>
			<key>name</key>
			<string>jsd.log.log</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>mcol_800080FF.settings</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.settings</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.settings</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\[T\])\s(.*?):(\d+)\s</string>
			<key>name</key>
			<string>jsd.log.tip</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>mcol_CC0000FF.settings</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.settings</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.settings</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\t(.+)\s(.*?):(\d+)</string>
			<key>name</key>
			<string>jsd.log.object</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.settings</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(.*?:)\s(.*?)$</string>
			<key>name</key>
			<string>jsd.log.property</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(.*?)$</string>
			<key>name</key>
			<string>jsd.log.property_object_name</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>jsd.log</string>
	<key>uuid</key>
	<string>ca03e751-04ef-4330-9a6b-9b99aae1c418</string>
</dict>
</plist>
